version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: sass-loader
  - dependency-name: stylelint-config-standard
  - dependency-name: node-sass
